sonar.projectKey=front-end-ts
sonar.projectName=Front-End-TS
sonar.sourceEncoding=UTF-8

# Diretórios que contêm os códigos-fonte a serem analisados
sonar.sources=src
# Arquivos/Diretórios a serem excluídos da análise de código-fonte
sonar.exclusions=**/*.test.tsx,**/*.test.ts,**/*.spec.tsx,**/*.spec.ts,**/*.stories.tsx,**/*.stories.ts,**/node_modules/**,**/.next/**,coverage/**

# Diretórios ou arquivos de testes
sonar.tests=src
# Quais arquivos devem ser considerados testes
sonar.test.inclusions=**/*.test.tsx,**/*.test.ts,**/*.spec.tsx,**/*.spec.ts

# Caminho para o relatório de cobertura gerado pelo Jest (lcov)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Arquivos a serem excluídos da métrica de cobertura (tipos, interfaces, etc.)
sonar.coverage.exclusions=**/*.stories.tsx,**/*.stories.ts,src/types/**,src/interfaces/**,src/**/*.d.ts
