name: Release

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Instalar dependências
        run: npm install

      - name: Rodar build
        run: npm run build

      - name: Testes unitarios
        run: npm test    
      #PARTE 1 - Até aqui

      #PARTE 2 - A partir daqui (descomentar)
      - name: Checkout do código
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Buscar tags


      - name: Instalar semver
        run: npm install -g semver
#
      - name: Criar nova tag caso não exista
        id: create_initial_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -z "$(git tag)" ]; then
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
            git tag -a v0.0.0 -m "Initial release"
            git push origin v0.0.0
          fi
#
      - name: Calcular nova versão
        id: version
        run: |
          git fetch --tags
          LAST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          if [ -z "$LAST_TAG" ]; then
            LAST_TAG="v0.0.0"
          fi
          echo "Versão Atual: $LAST_TAG"
          
          if [ "$LAST_TAG" = "v0.0.0" ]; then
            COMMITS=$(git log --pretty=format:"%s")
          else
            COMMITS=$(git log ${LAST_TAG}..HEAD --pretty=format:"%s")
          fi
          
          echo "Commits desde a última tag:"
          echo "$COMMITS"
          
          # Inicializando variáveis
          MAJOR=0
          MINOR=0
          PATCH=0
          
          # Analisando mensagens de commit
          for COMMIT in "$COMMITS"; do
            if [[ "$COMMIT" == *"BREAKING CHANGE"* ]]; then
              MAJOR=1
            elif [[ "$COMMIT" == *"feat"* ]]; then
              MINOR=1
            elif [[ "$COMMIT" == *"fix"* ]]; then
              PATCH=1
            fi
          done
          
          # Calculando a nova versão usando semver
          CURRENT_VERSION=${LAST_TAG#v}
          NEW_VERSION=$CURRENT_VERSION
          if [[ $MAJOR -eq 1 ]]; then
            NEW_VERSION=$(semver -i major $CURRENT_VERSION)
          elif [[ $MINOR -eq 1 ]]; then
            NEW_VERSION=$(semver -i minor $CURRENT_VERSION)
          elif [[ $PATCH -eq 1 ]]; then
            NEW_VERSION=$(semver -i patch $CURRENT_VERSION)
          fi
          
          echo "Nova versão: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
#
      - name: Atualizar versão no package.json
        run: |
          npm version ${{ steps.version.outputs.new_version }} --no-git-tag-version
          
      - name: Commit e push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git add package.json
          git commit -m "chore(release): version ${{ steps.version.outputs.new_version }}"
          git tag v${{ steps.version.outputs.new_version }}
          git push origin main --tags

      - name: Enviar email em caso de falha
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  # Update to your SMTP server
          server_port: 587
          username: ${{ secrets.EMAIL_ORIGIN }}
          password: ${{ secrets.EMAIL_APP_PASSWORD }}  # Use app password, not regular password
          subject: "Falha no CI - Back-End-TS"
          body: "O processo de CI falhou. Por favor, verifique os logs para mais detalhes."
          to: ${{ secrets.EMAIL_DESTINO }}
          from: ${{ secrets.EMAIL_ORIGIN }}   